feat: Upgrade to CKAN 2.11.0 official Docker image
tum-gis/ckan-docker pull request #71
Opened 2024-11-14 08:58 UTC by aleksandralazoroska

2024-12-20 12:55 UTC, tino097 commented on sddi-base/Dockerfile
> +
```
  ckan config-tool "${CKAN_INI}" "PERMANENT_SESSION_LIFETIME = 600" && \
  ckan config-tool "${CKAN_INI}" "ckanext.security.redis.host = redis" && \
  ckan config-tool "${CKAN_INI}" "ckanext.security.redis.port = 6379" && \
  ckan config-tool "${CKAN_INI}" "ckanext.security.redis.db = 1"
  ```

2025-02-14 12:40 UTC, BWibo reviewed
See the comments above. There is one general issue that should be fixed. There are a lots of duplications beween `base` and `sddi` image variant.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> -FROM ckan/ckan-base:${CKAN_VERSION_BUILD_STAGE} as extbuild
Why did you remove the build args. The give us flexibility to try out things without changing the Dockerfile. Please re-add.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +ARG CKANEXT_HIERARCHY_VERSION="abb4e2d"
Is there a stable version number we can use instead?

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +  pip3 wheel --wheel-dir=/wheels git+${ENVVARS_GIT_URL}@${ENVVARS_GIT_BRANCH}#egg=ckanext-envvars
Let's consistently uses `pip` or `pip3`. I prefer `pip`.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +ENV ENVVARS_GIT_BRANCH=v0.0.6
I suggest we stick a consistent naming for theses variables. `CKANEXT_XXXX_VERSION` is used for the other extensions.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +ARG CKANEXT_SCHEMING_VERSION="27035f4"
Is there a stable release version we can use?

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +ENV UWSGI_HARAKIRI=50
Most of these variables are already introduced in the base image. Please remove all redundancies.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +    sudo
This is a lot of dependencies being installed. Are all of those packages really required. Please check and remove anything we don't need. For instance, `sudo` should not rather not exists in a Docker image.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +    ln -s /usr/bin/python3 /usr/bin/python
I would remove this and rather install `apt install python-is-python3`. This is the OS native way to handle this.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +
What are those dependencies needed for? Are you sure they don't exist in the `requirements.txt` of the extensions?
This is a source for dependency issue in the future. If possible, remove.

2025-02-14 12:40 UTC, BWibo commented on sddi-base/Dockerfile
> +
I would try to avoid hardcoding this. Or is this just defaults, that we can override with env vars?

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +FROM ckan/ckan-base:2.11.1 as extbuild
Same as above, please re-insert the build args.

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +ENV CKANEXT_RELATION_VERSION=${CKANEXT_RELATION_VERSION}
Those extensions are already build and added in the base image. Check for all extensions, that they are only build and installed in either `base` or `sddi` variant.

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +ENV CKANEXT_SECURITY_GITHUB_URL="https://github.com/MarijaKnezevic/ckanext-security"
Same as above. Check for duplicate build/install with `base`

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +ARG CKANEXT_SECURITY_VERSION="5724341"
Is there a stable vesion nr we can use?

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +ARG CKANEXT_CLAMAV_VERSION="a1d23ac"
Is there a stable version we can ise instead?

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +ENV UWSGI_HARAKIRI=50
Same as in `base`. Check for duplication with ckan base image.

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +RUN update-locale LANG=${LC_ALL}
Is something similar done in the base image?

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +    sudo
Check for duplication with `base` and `ckan` base image.

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +    ln -s /usr/bin/python3 /usr/bin/python
See comment on base image.

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +
See comment on base image.

2025-02-14 12:40 UTC, BWibo commented on sddi/Dockerfile
> +  ckan config-tool "${CKAN_INI}" "PERMANENT_SESSION_LIFETIME = 600"
Is it required for all these settings to set them here? Can we overwrite all of those settings?

2025-02-14 12:47 UTC, MarijaKnezevic commented on sddi-base/Dockerfile
> -FROM ckan/ckan-base:${CKAN_VERSION_BUILD_STAGE} as extbuild
@ilchebedelovski @aleksandralazoroska can you please take care for this?

2025-02-14 12:50 UTC, MarijaKnezevic commented on sddi-base/Dockerfile
> +  pip3 wheel --wheel-dir=/wheels git+${ENVVARS_GIT_URL}@${ENVVARS_GIT_BRANCH}#egg=ckanext-envvars
@aleksandralazoroska @ilchebedelovski can you please check this?

2025-02-14 12:51 UTC, MarijaKnezevic commented on sddi-base/Dockerfile
> +ARG CKANEXT_SCHEMING_VERSION="27035f4"
@BWibo Unfortunately not. The same case as with `ckanext-hierarchy`

2025-02-14 12:52 UTC, MarijaKnezevic commented on sddi-base/Dockerfile
> +    sudo
@aleksandralazoroska @ilchebedelovski can you please check this?

2025-02-14 12:52 UTC, MarijaKnezevic commented on sddi-base/Dockerfile
> +    ln -s /usr/bin/python3 /usr/bin/python
@aleksandralazoroska @ilchebedelovski can you please check this?

2025-02-14 12:53 UTC, MarijaKnezevic commented on sddi-base/Dockerfile
> +
@aleksandralazoroska @ilchebedelovski can you please check this?

2025-02-14 12:53 UTC, MarijaKnezevic commented on sddi/Dockerfile
> +FROM ckan/ckan-base:2.11.1 as extbuild
@aleksandralazoroska @ilchebedelovski can you please check this?

2025-02-14 12:55 UTC, MarijaKnezevic commented on sddi/Dockerfile
> +ARG CKANEXT_SECURITY_VERSION="5724341"
@BWibo Unfortunately not. The same case as with `ckanext-hierarchy`

2025-02-14 12:55 UTC, MarijaKnezevic commented on sddi/Dockerfile
> +ARG CKANEXT_CLAMAV_VERSION="a1d23ac"
@BWibo Unfortunately not. The same case as with `ckanext-hierarchy`

2025-02-15 15:59 UTC, BWibo commented
The build currently fails with this:

```text
#4 [1/4] FROM ghcr.io/tum-gis/ckan-sddi-dev:sddi-base-pr-71-0530154
#4 DONE 0.1s

#5 [3/4] ADD https://raw.githubusercontent.com/ckan/ckan/ckan-2.9.9/dev-requirements.txt /dev-requirements.txt
#5 DONE 0.2s

#6 [2/4] RUN mkdir /docker-entrypoint.d
#6 0.132 mkdir: cannot create directory ‘/docker-entrypoint.d’: File exists
#6 ERROR: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1

#5 [3/4] ADD https://raw.githubusercontent.com/ckan/ckan/ckan-2.9.9/dev-requirements.txt /dev-requirements.txt
#5 DONE 0.2s
------
 > [2/4] RUN mkdir /docker-entrypoint.d:
0.132 mkdir: cannot create directory ‘/docker-entrypoint.d’: File exists
------
Dockerfile.debug:1
--------------------
   1 | >>> ARG BASEIMAGE_REPOSITORY=ghcr.io/tum-gis/ckan-sddi-base
   2 |     ARG BASEIMAGE_VERSION=edge
   3 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
```

2025-02-16 10:35 UTC, ilchebedelovski commented
> The build currently fails with this:
> 
> 
> 
> ```text
> 
> #4 [1/4] FROM ghcr.io/tum-gis/ckan-sddi-dev:sddi-base-pr-71-0530154
> 
> #4 DONE 0.1s
> 
> 
> 
> #5 [3/4] ADD https://raw.githubusercontent.com/ckan/ckan/ckan-2.9.9/dev-requirements.txt /dev-requirements.txt
> 
> #5 DONE 0.2s
> 
> 
> 
> #6 [2/4] RUN mkdir /docker-entrypoint.d
> 
> #6 0.132 mkdir: cannot create directory ‘/docker-entrypoint.d’: File exists
> 
> #6 ERROR: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
> 
> 
> 
> #5 [3/4] ADD https://raw.githubusercontent.com/ckan/ckan/ckan-2.9.9/dev-requirements.txt /dev-requirements.txt
> 
> #5 DONE 0.2s
> 
> ------
> 
>  > [2/4] RUN mkdir /docker-entrypoint.d:
> 
> 0.132 mkdir: cannot create directory ‘/docker-entrypoint.d’: File exists
> 
> ------
> 
> Dockerfile.debug:1
> 
> --------------------
> 
>    1 | >>> ARG BASEIMAGE_REPOSITORY=ghcr.io/tum-gis/ckan-sddi-base
> 
>    2 |     ARG BASEIMAGE_VERSION=edge
> 
>    3 |     
> 
> --------------------
> 
> ERROR: failed to solve: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
> 
> Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
> 
> ```

Hey @BWibo thanks for the review, actually the build is failing because of the code in the Dockerfile.debug files, I even changed the FROM image version to 2.11.1 and again we have the some issue.

Is it ok for you to comment/remove the build part for the .debug images? The upgrade to 2.11.1 is not dependent on the .debug stages and that part is blocking our progress to making a final release for 2.11.1.

2025-02-17 08:56 UTC, BWibo requested changes

2025-02-17 08:56 UTC, BWibo commented on sddi/Dockerfile
> -FROM ${BASEIMAGE_REPOSITORY}:${BASEIMAGE_VERSION} as runtime
The `sddi` image needs use our `base` image as base.
@MarijaKnezevic Discuss with @aleksandralazoroska @ilchebedelovski which extension go in which Dockerfile.

2025-02-17 21:28 UTC, ilchebedelovski commented on sddi-base/Dockerfile
> +
The harvest configuration is fully removed from the Dockerfile.

2025-02-17 21:29 UTC, ilchebedelovski commented
> @ilchebedelovski It's working now, so your comment above is obsolete, right? In general I would like to keep the debug image, otherwise we would have to change documentaition too.

Yes, now looks good, thanks.

2025-02-17 21:30 UTC, ilchebedelovski commented on sddi/Dockerfile
> -FROM ${BASEIMAGE_REPOSITORY}:${BASEIMAGE_VERSION} as runtime
The extensions are solved, part of them are in sddi-base and the rest of them are in sddi according to the documentation in the Readme file.

2025-02-17 21:31 UTC, ilchebedelovski commented on sddi-base/Dockerfile
> +ENV ENVVARS_GIT_BRANCH=v0.0.6
The naming has been solved.

2025-02-17 21:32 UTC, ilchebedelovski commented on sddi-base/Dockerfile
> +  pip3 wheel --wheel-dir=/wheels git+${ENVVARS_GIT_URL}@${ENVVARS_GIT_BRANCH}#egg=ckanext-envvars
`pip3` has been replaced with `pip`.

2025-02-17 21:33 UTC, ilchebedelovski commented on sddi/Dockerfile
> +RUN update-locale LANG=${LC_ALL}
The repeated lines are removed.

2025-03-19 13:37 UTC, BWibo requested changes
There are some small things left, discuss them with @MarijaKnezevic.

2025-03-19 13:37 UTC, BWibo commented on sddi-base/Dockerfile
>  ENV CKAN_INI=${APP_DIR}/production.ini
In ckan-docker-base this is `ENV CKAN_INI=${APP_DIR}/production.ini`. Is there a specific reason why we use a different configuration file?

2025-03-19 13:37 UTC, BWibo commented on sddi-base/Dockerfile
> +    uwsgi-plugin-python3
Do we need the `*-dev` version of those packages? If possible, use the non dev version.

2025-03-19 13:37 UTC, BWibo commented on sddi/Dockerfile
> +RUN pip install -U markupsafe==2.0.1 sqlalchemy==1.4.41
Official CKAN 2.11.1 uses different version for those packages. Is there a specific reason why you install those version?
If no, please remove this line.

2025-03-19 13:37 UTC, BWibo commented on sddi/Dockerfile
> +ENV CKAN_INI=${APP_DIR}/production.ini
Same as sddi-base/Dockerfile, see above.

2025-03-19 13:37 UTC, BWibo commented on sddi/Dockerfile
> +HEALTHCHECK --interval=60s --timeout=5s --retries=5 CMD curl --fail http://localhost:5000/api/3/action/status_show || exit CMD ["/srv/app/start_ckan.sh"]
This won't work if somebody changes the CKAN port. Is there a variable you can use here?

2025-03-19 13:37 UTC, BWibo commented on sddi-base/Dockerfile
> +HEALTHCHECK --interval=60s --timeout=5s --retries=5 CMD curl --fail http://localhost:5000/api/3/action/status_show || exit CMD ["/srv/app/start_ckan.sh"]
This won't work if somebody changes the CKAN port. Is there a variable you can use here?

2025-03-19 18:44 UTC, ilchebedelovski commented on sddi/Dockerfile
> +HEALTHCHECK --interval=60s --timeout=5s --retries=5 CMD curl --fail http://localhost:5000/api/3/action/status_show || exit CMD ["/srv/app/start_ckan.sh"]
CKAN has used port 5000 since 2006, if somebody changes the port I am sure that many other things will be changed and we will need to adapt to all of them somehow.

The port is hardcoded in the base image as well https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.11/Dockerfile#L108.

2025-03-19 18:44 UTC, ilchebedelovski commented on sddi-base/Dockerfile
> +HEALTHCHECK --interval=60s --timeout=5s --retries=5 CMD curl --fail http://localhost:5000/api/3/action/status_show || exit CMD ["/srv/app/start_ckan.sh"]
CKAN has used port 5000 since 2006, if somebody changes the port I am sure that many other things will be changed and we will need to adapt to all of them somehow.

The port is hardcoded in the base image as well https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.11/Dockerfile#L108.

2025-03-19 18:54 UTC, ilchebedelovski commented on sddi-base/Dockerfile
> +    uwsgi-plugin-python3
Correct me if I am wrong, but `-dev` version of the packages is used because some CKAN extensions need to build/compile against the packages such as musl, libssl, libproj etc, not because those packages cannot be used for production.

Those packages are used in the official Dockerfile for the lower CKAN versions as well https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.10/Dockerfile#L49-L79.

2025-03-21 15:09 UTC, ilchebedelovski approved these changes

2025-03-21 17:20 UTC, MarijaKnezevic commented
After the proposed changes, the repository is ready for release 3.0.0.

2025-03-21 17:21 UTC, merged